export const recipes = [
  {
    id: 1,
    name: "Kung Pao Chicken",
    difficulty: "easy",
    description:
      "A spicy stir-fry dish with chicken, peanuts, vegetables, and chili peppers",
    image: "/images/guzheng.jpg", // Reusing existing images as placeholders
    region: "Sichuan",
    preparationTime: "25 minutes",
    ingredients: [
      "Chicken",
      "Peanuts",
      "Bell Peppers",
      "Dried Chili",
      "Sichuan Peppercorns",
      "Soy Sauce",
    ],
    steps: [
      "Dice chicken into small cubes",
      "Dry-fry the peanuts",
      "Stir-fry chicken until golden",
      "Add vegetables and spices",
      "Mix in sauce and peanuts",
      "Serve hot with rice",
    ],
    funFact:
      "Kung Pao chicken is named after a Qing Dynasty official, Ding Baozhen, whose title was 'Gong Bao'",
  },
  {
    id: 2,
    name: "Dim Sum",
    difficulty: "medium",
    description: "A variety of small dishes traditionally served with tea",
    image: "/images/erhu.jpg", // Reusing existing images as placeholders
    region: "Cantonese",
    preparationTime: "45 minutes",
    ingredients: [
      "Wheat Flour",
      "Rice Flour",
      "Shrimp",
      "Pork",
      "Bamboo Shoots",
      "Shiitake Mushrooms",
    ],
    steps: [
      "Prepare the dough",
      "Mix filling ingredients",
      "Wrap filling in dough",
      "Steam for 8-10 minutes",
      "Serve with dipping sauces",
      "Enjoy with tea",
    ],
    funFact:
      "Dim Sum means 'touch the heart' in Cantonese and originated from teahouses along the Silk Road",
  },
  {
    id: 3,
    name: "Peking Duck",
    difficulty: "hard",
    description: "Famous roast duck known for its thin, crispy skin",
    image: "/images/pipa.jpg", // Reusing existing images as placeholders
    region: "Beijing",
    preparationTime: "2 days",
    ingredients: [
      "Whole Duck",
      "Honey",
      "Chinese Five Spice",
      "Soy Sauce",
      "Scallions",
      "Cucumber",
    ],
    steps: [
      "Clean and dry the duck",
      "Air-dry for 24 hours",
      "Brush with honey mixture",
      "Roast until crispy",
      "Slice the meat and skin",
      "Serve with pancakes",
    ],
    funFact:
      "Peking Duck dates back to the imperial era and was prepared for the Emperor of China in the Yuan Dynasty",
  },
  {
    id: 4,
    name: "Mapo Tofu",
    difficulty: "easy",
    description: "Spicy tofu dish with minced meat in fermented bean sauce",
    image: "/images/dizi.jpg", // Reusing existing images as placeholders
    region: "Sichuan",
    preparationTime: "20 minutes",
    ingredients: [
      "Soft Tofu",
      "Ground Pork",
      "Doubanjiang",
      "Sichuan Peppercorns",
      "Garlic",
      "Green Onions",
    ],
    steps: [
      "Cut tofu into cubes",
      "Stir-fry ground pork",
      "Add doubanjiang and spices",
      "Gently add tofu",
      "Simmer for 5 minutes",
      "Sprinkle with peppercorns",
    ],
    funFact:
      "Mapo Tofu was created by a pockmarked (ma) woman (po) in the 1800s, which is how the dish got its name",
  },
  {
    id: 5,
    name: "Hot Pot",
    difficulty: "medium",
    description:
      "A communal meal with a simmering pot of soup stock and various ingredients",
    image: "/images/yangqin.jpg", // Reusing existing images as placeholders
    region: "Chongqing",
    preparationTime: "40 minutes",
    ingredients: [
      "Beef Slices",
      "Fish Balls",
      "Tofu",
      "Napa Cabbage",
      "Enoki Mushrooms",
      "Chili Oil",
    ],
    steps: [
      "Prepare broth with spices",
      "Arrange raw ingredients",
      "Heat broth to boiling",
      "Cook ingredients in broth",
      "Dip in sauce before eating",
      "Add more broth as needed",
    ],
    funFact:
      "Hot pot has a history of over 1,000 years and was originally used by Mongolian warriors who used their helmets as cooking vessels",
  },
  {
    id: 6,
    name: "Spring Rolls",
    difficulty: "easy",
    description:
      "Cylindrical pastries filled with vegetables and sometimes meat",
    image: "/images/gong.jpg", // Reusing existing images as placeholders
    region: "Various regions",
    preparationTime: "30 minutes",
    ingredients: [
      "Spring Roll Wrappers",
      "Bean Sprouts",
      "Carrots",
      "Cabbage",
      "Mushrooms",
      "Garlic",
    ],
    steps: [
      "Chop vegetables finely",
      "Stir-fry filling until soft",
      "Let filling cool",
      "Wrap filling in wrappers",
      "Deep fry until golden",
      "Serve with dipping sauce",
    ],
    funFact:
      "Spring rolls got their name because they were traditionally eaten during the Spring Festival to welcome the new season",
  },
  {
    id: 7,
    name: "Xiaolongbao",
    difficulty: "hard",
    description:
      "Soup dumplings with a thin wrapper filled with meat and rich broth",
    image: "/images/dizi.jpg",
    region: "Shanghai",
    preparationTime: "2 hours",
    ingredients: [
      "Flour",
      "Ground Pork",
      "Gelatin",
      "Ginger",
      "Sesame Oil",
      "Green Onions",
    ],
    steps: [
      "Make gelatin-rich broth",
      "Chill until solid",
      "Dice and mix with meat",
      "Roll out thin wrappers",
      "Fold dumplings carefully",
      "Steam for 8 minutes",
    ],
    funFact:
      "Xiaolongbao gets its soup filling from gelatin that melts during cooking, creating the signature soupy interior",
  },
  {
    id: 8,
    name: "Zhajiangmian",
    difficulty: "medium",
    description:
      "Hand-pulled noodles topped with minced pork in fermented soybean sauce",
    image: "/images/guzheng.jpg",
    region: "Beijing",
    preparationTime: "35 minutes",
    ingredients: [
      "Wheat Noodles",
      "Ground Pork",
      "Sweet Bean Sauce",
      "Cucumber",
      "Garlic",
      "Soybean Paste",
    ],
    steps: [
      "Prepare fresh noodles",
      "Stir-fry ground pork",
      "Add sweet bean sauce",
      "Simmer sauce until thick",
      "Cook and drain noodles",
      "Top noodles with sauce and vegetables",
    ],
    funFact:
      "Zhajiangmian is often called 'Chinese spaghetti bolognese' but dates back over 300 years, predating Italian influence",
  },
  {
    id: 9,
    name: "Char Siu",
    difficulty: "medium",
    description: "Cantonese-style barbecued pork with a sweet and savory glaze",
    image: "/images/pipa.jpg",
    region: "Guangdong",
    preparationTime: "24 hours",
    ingredients: [
      "Pork Shoulder",
      "Hoisin Sauce",
      "Five-Spice Powder",
      "Soy Sauce",
      "Honey",
      "Red Food Coloring",
    ],
    steps: [
      "Slice pork into strips",
      "Marinate overnight",
      "Prepare roasting rack",
      "Roast and baste regularly",
      "Rest meat before slicing",
      "Reduce marinade for sauce",
    ],
    funFact:
      "The signature red color traditionally comes from red fermented bean curd, though many restaurants now use food coloring",
  },
  {
    id: 10,
    name: "Congee",
    difficulty: "easy",
    description:
      "Comforting rice porridge that can be served plain or with various toppings",
    image: "/images/yangqin.jpg",
    region: "All over China",
    preparationTime: "1 hour",
    ingredients: [
      "Rice",
      "Chicken Stock",
      "Ginger",
      "Century Egg",
      "Green Onions",
      "White Pepper",
    ],
    steps: [
      "Rinse rice thoroughly",
      "Simmer rice in stock",
      "Stir occasionally",
      "Cook until creamy",
      "Add toppings of choice",
      "Season to taste",
    ],
    funFact:
      "Congee is considered a healing food in Chinese medicine and is often served to those who are ill to aid recovery",
  },
  {
    id: 11,
    name: "Dan Dan Noodles",
    difficulty: "medium",
    description:
      "Spicy Sichuan noodles with chili oil, minced pork and preserved vegetables",
    image: "/images/erhu.jpg",
    region: "Sichuan",
    preparationTime: "30 minutes",
    ingredients: [
      "Wheat Noodles",
      "Ground Pork",
      "Chili Oil",
      "Sichuan Peppercorns",
      "Preserved Vegetables",
      "Sesame Paste",
    ],
    steps: [
      "Make chili oil mixture",
      "Brown ground pork",
      "Boil noodles until al dente",
      "Mix sauce ingredients",
      "Combine noodles with sauce",
      "Top with meat and peanuts",
    ],
    funFact:
      "The name comes from the carrying pole (dan dan) that street vendors used to carry their noodles and cooking equipment",
  },
  {
    id: 12,
    name: "Beggar's Chicken",
    difficulty: "hard",
    description:
      "Whole chicken wrapped in lotus leaves and clay, then baked until tender",
    image: "/images/gong.jpg",
    region: "Hangzhou",
    preparationTime: "4 hours",
    ingredients: [
      "Whole Chicken",
      "Lotus Leaves",
      "Shaoxing Wine",
      "Mushrooms",
      "Clay or Dough",
      "Ginger",
    ],
    steps: [
      "Marinate the chicken",
      "Stuff with mushrooms and ham",
      "Wrap in lotus leaves",
      "Seal in clay or dough",
      "Bake for 3 hours",
      "Crack open at the table",
    ],
    funFact:
      "Legend says a beggar stole a chicken and buried it in mud to cook it without detection, accidentally creating this delicious dish",
  },
];
